services:
  postgres:
    image: postgres:latest
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 2s
      retries: 5
      start_period: 10s

  redis:
    image: redis/redis-stack-server:latest
    container_name: redis
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 5s
      timeout: 2s
      retries: 5
      start_period: 10s


  api:
    container_name: api
    image: weather-api-image:latest
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    command: sh -c 'uv run uvicorn main:app --host 0.0.0.0 --port 8000 --reload'
    env_file:
      - .env
    ports:
      - "8000:8000"
    # volumes:
    #   - .:/wheather/backend
    #   - /wheather/backend/.venv
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /Weather
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy


  celery_worker:
      container_name: celery_worker
      image: weather-api-image:latest
      restart: unless-stopped
      command: sh -c 'uv run celery -A core.celery.worker.app worker --loglevel=info'
      env_file:
        - .env
      develop:
        watch:
          - action: sync
            path: ./backend
            target: /Weather
      depends_on:
        postgres:
          condition: service_healthy
        redis:
          condition: service_healthy
        api:
          condition: service_started


  frontend:
    container_name: frontend
    image: weather-frontend-image:latest
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "4200:80"
    depends_on:
      - api
